/* v5表示層。採点はすべて data.js の公開関数だけを利用する。 */
const $ = s => document.querySelector(s);
const state={index:0,log:[],checks:[],extra:[],name:'あなた',stage:'',audience:'',urgentPrimaryIssue:false};
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo({top:0,behavior:'smooth'});}
function allQuestions(){return [...BASE,...state.extra];}
function renderQuestion(){const q=allQuestions()[state.index];$('#count').textContent=`${state.index+1}問目 / ${allQuestions().length}問`;$('#chapter').textContent='いつもの決め方';$('#bar').style.width=`${(state.index+1)/allQuestions().length*100}%`;$('#scene').textContent=`場面：${q.scene}`;$('#question').textContent=q.q;$('#talk').textContent='正解ではなく、いつもの自分に近い方を選んでください。';$('#back').hidden=!state.index;$('#answers').innerHTML='';q.a.forEach((x,i)=>{const b=document.createElement('button');b.innerHTML=`<b>${'ABCD'[i]}</b>${x}`;b.onclick=()=>answer(q,i);$('#answers').append(b);});}
function answer(q,i){state.log.push(q.type[i]);state.index++;if(state.index<allQuestions().length)return renderQuestion();if(state.extra.length<2&&isNearTie(scoreTypes(state.log))){const top=scoreTypes(state.log).slice(0,2).map(x=>x[0]);state.extra.push(buildExtraQuestion(top,state.extra.length));return renderQuestion();}startChecks();}
function back(){if(!state.index)return;state.index--;state.log.pop();renderQuestion();}
function startChecks(){state.checkIndex=0;show('check');renderCheck();}
function renderCheck(){const q=CHECKS[state.checkIndex];$('#checkStep').textContent=`現在の確認 ${state.checkIndex+1} / ${CHECKS.length}`;$('#checkQuestion').textContent=q.q;$('#checkAnswers').innerHTML='';q.a.forEach((x,i)=>{const b=document.createElement('button');b.innerHTML=`<b>${'ABCD'[i]}</b>${x}`;b.onclick=()=>{state.checks[state.checkIndex]=i;if(++state.checkIndex<CHECKS.length)renderCheck();else result();};$('#checkAnswers').append(b);});}
function checkBack(){if(!state.checkIndex){show('quiz');return renderQuestion();}state.checkIndex--;renderCheck();}
function result(){const ranks=scoreTypes(state.log),id=ranks[0][0],t=TYPES[id],issues=scoreIssues(state.checks),axes=normalizedAxes(state.log.slice(0,BASE.length));const eligible=storyOfferEligible({issues,stage:state.stage,audience:state.audience,urgentPrimaryIssue:state.urgentPrimaryIssue});state.resultType=id;state.resultAxes=axes;$('#resultName').textContent=state.name;$('#mainType').textContent=t.name;$('#tagline').textContent=t.tag;$('#mix').textContent='今回の回答で中心に出た傾向です。能力の優劣ではありません。';$('#axisList').innerHTML=AXES.map((x,i)=>`<span><b>${x}</b><strong>${axes[i]}</strong><small>今回の回答傾向</small></span>`).join('');$('#reasonIntro').textContent='選んだ場面から、今の経営で大切にしやすいことを読み取りました。';$('#evidence').innerHTML=`<article><p>今回の中心傾向</p><b>${t.tag}</b></article>`;$('#strengthTitle').textContent=t.strength;$('#strength').textContent='今回の回答では、この場面で力が生きやすい傾向が出ています。';$('#risk').textContent=t.risk;const entries=Object.entries(issues);const lead=entries.sort((a,b)=>b[1].score-a[1].score)[0];$('#issues').innerHTML=entries.map(([k,v])=>`<span>${k}（${v.status}）</span>`).join('')||'<span>今は大きな詰まりなし</span>';$('#issueTitle').textContent=lead?`今、先に整えたいのは\n${lead[0]}`:'今、先に整えたいこと';$('#issueText').textContent=lead?`今回の確認では「${lead[0]}」が${lead[1].status}として出ました。タイプとは別に、今の状況として小さく確かめてください。`:'回答からは、優先する課題はまだはっきり確認できませんでした。';$('#actionTitle').textContent=t.action;$('#actionText').textContent=t.actionText;$('#storyOffer').hidden=!eligible;$('#otherOffer').hidden=eligible;if(eligible){$('#storyReason').textContent=`「構想を整理・言葉にすること」が複数の回答で確認でき、${state.audience}へ伝えたい時期でもあります。まず無料の見本で、構想を物語にすると何が変わるかを確かめてください。`;}else{$('#otherTitle').textContent=state.urgentPrimaryIssue?'まずは、緊急対応を優先してください':'まずは、今週の一歩から';$('#otherText').textContent=state.urgentPrimaryIssue?'資金繰り・法律・人の問題は、関係者や専門家への相談を優先してください。':'今の課題を小さく確かめてから、必要な解決策を選びましょう。';}show('result');}
function share(){const url=new URL('share-result.html',location.href);url.searchParams.set('type',state.resultType);url.searchParams.set('name',state.name);url.searchParams.set('axes',state.resultAxes.join(','));return{text:`私は「${$('#mainType').textContent}」でした。${$('#tagline').textContent}\n経営の現在地診断`,url:url.href};}
$('#startBtn').onclick=()=>show('profile');$('#profileNext').onclick=()=>{state.name=$('#name').value.trim()||'あなた';state.stage=$('#stage').value;state.audience=$('#audience').value;state.urgentPrimaryIssue=$('#urgent').value==='yes';show('quiz');renderQuestion();};$('#back').onclick=back;$('#checkBack').onclick=checkBack;$('#retry').onclick=()=>location.reload();$('#nativeShare').onclick=()=>navigator.share&&navigator.share(share());$('#lineShare').onclick=()=>open('https://line.me/R/msg/text/?'+encodeURIComponent(share().text+'\n'+share().url),'_blank');$('#xShare').onclick=()=>open('https://twitter.com/intent/tweet?text='+encodeURIComponent(share().text)+'&url='+encodeURIComponent(share().url),'_blank');$('#copyShare').onclick=async()=>{await navigator.clipboard.writeText(share().text+'\n'+share().url);$('#shareStatus').textContent='リンクをコピーしました。';};
