const TYPES = {
  T01:{name:"事業開拓型",tag:"思いついたら、まず道をつくる人。",strength:"まだ形のない話を面白がり、最初の一歩を踏み出せます。止まっている場に勢いをつくるのが得意です。",risk:"新しい案が次々に出るため、途中の仕事や周りへの説明が置き去りになりがちです。",counter:"新しい案を始める前に『誰のため・何をする・いつまで』の3行だけ書き、今ある仕事を一つ終わらせましょう。",today:"頭にある新しい案を、3行で書く",figure:"坂本龍馬"},
  T02:{name:"仕組み経営型",tag:"がんばらなくても回る形をつくる人。",strength:"数字や手順を整え、同じ成果が続く状態をつくれます。無駄や抜けに気づく力があります。",risk:"整えることを優先しすぎると、お客様の気持ちや現場の小さな変化を見落とします。",counter:"仕組みを直す前に、現場の人とお客様へ一つずつ質問してください。数字と生の声を一緒に見ましょう。",today:"繰り返している作業を一つ書き出す",figure:"二宮尊徳"},
  T03:{name:"組織拡大型",tag:"仲間を集め、大きな力に変える人。",strength:"人に役割を渡し、チームで大きな仕事を動かせます。場をまとめ、前へ進める力があります。",risk:"人数と仕事が増えるほど、利益や一人ひとりの納得が見えにくくなります。",counter:"目標だけでなく『なぜ今これをするか』を短く繰り返し伝え、月に一度は利益と負担の両方を確認しましょう。",today:"一人に仕事ではなく目的を伝える",figure:"豊臣秀吉"},
  T04:{name:"市場攻略型",tag:"売れる場所と見せ方を見つける人。",strength:"相手の反応を見ながら、言葉・見せ方・売り方を素早く変えられます。",risk:"反応を追いすぎると、商品が本来届けたかった価値や長い信頼が薄くなります。",counter:"売れた数だけでなく『買ったあと、どう良くなったか』を聞いてください。短い成果と長い信頼を分けて見ます。",today:"最近のお客様一人に感想を聞く",figure:"紀伊國屋文左衛門"},
  T05:{name:"志実現型",tag:"大きな夢を、仕事に変えていく人。",strength:"自分が本当にやりたい未来を描き、人をわくわくさせられます。",risk:"理想が大きいほど、今日やる仕事やお金の話が後回しになりやすいです。",counter:"夢を『今月できる小さな実験』へ落としましょう。応援してくれる人だけでなく、厳しい数字も一緒に見ます。",today:"夢に近づく一番小さな実験を決める",figure:"渋沢栄一"},
  T06:{name:"資本戦略型",tag:"お金の流れから、次の一手を考える人。",strength:"資金や投資の組み合わせを考え、事業を大きく動かす選択ができます。",risk:"条件や効率を重く見ると、商品を使う人や働く人の気持ちが遠くなります。",counter:"数字の判断に『お客様に何が残るか』『現場に何が起きるか』の二つを加えてください。",today:"次の投資で得たい結果を一つに絞る",figure:"岩崎弥太郎"},
  T07:{name:"品質追求型",tag:"納得できるものを、ていねいにつくる人。",strength:"小さな違いに気づき、信頼される商品や仕事をつくり込めます。",risk:"十分よい状態でも出せず、売る・伝える・人に任せる時期が遅れがちです。",counter:"完成の基準を先に決め、まず少人数へ見せましょう。感想をもらって直すことも品質づくりです。",today:"今ある商品を一人に見せる",figure:"千利休"},
  T08:{name:"社会使命型",tag:"世の中の困りごとを、仕事で変える人。",strength:"利益だけでは見過ごされる問題を見つけ、意味のある仕事へ変えられます。",risk:"意義を優先するほど、続けるための売上や値付けを遠ざけてしまいます。",counter:"助けたい人を具体的に一人決め、その人が無理なく払える価値と、事業が続く価格を両方考えましょう。",today:"助けたい一人の顔を思い浮かべる",figure:"緒方洪庵"},
  T09:{name:"発信牽引型",tag:"自分の言葉で、人を動かす人。",strength:"思いや経験を魅力的に伝え、共感する人を集められます。",risk:"社長本人に注目が集まりすぎると、商品や会社が一人に頼った状態になります。",counter:"自分の話だけでなく、お客様や仲間が主役になる話も発信しましょう。発信を他の人が続けられる型にします。",today:"お客様が主役の話を一つ発信する",figure:"高杉晋作"},
  T10:{name:"永続経営型",tag:"守るものを大切に、長く続ける人。",strength:"積み重ねた信用や文化を大切にし、安定して仕事を続けられます。",risk:"失敗を避ける気持ちが強いと、変えるべき時にも昔のやり方を手放せません。",counter:"残すものと変えるものを分けてください。大切なものを守るための小さな変更から試します。",today:"絶対に残したいものを一つ決める",figure:"徳川家康"}
};

const QUESTIONS = [
 {scene:"朝、思いついたとき",q:"新しい商売のアイデアが浮かんだ。まず何をする？",a:[["小さく試してみる","T01","T05"],["売れそうな相手を探す","T04","T09"],["お金と手順を計算する","T02","T06"],["詳しい人に相談する","T03","T10"]]},
 {scene:"仕事が増えてきたとき",q:"自分だけでは回らなくなってきた。どうする？",a:[["仲間を増やして役割を分ける","T03","T10"],["手順を決めて誰でもできるようにする","T02","T07"],["やらない仕事を決める","T06","T04"],["面白い部分は自分で続ける","T01","T05"]]},
 {scene:"商品を出す前",q:"新商品は7割できた。あなたなら？",a:[["まず少人数に売ってみる","T01","T04"],["納得するまで直してから出す","T07","T10"],["発表して期待を集める","T09","T05"],["利益が出るかもう一度見る","T06","T02"]]},
 {scene:"会議で意見が割れたとき",q:"最後は何を大事にして決める？",a:[["お客様が喜ぶか","T04","T07"],["会社の思いに合うか","T05","T08"],["数字として続くか","T02","T06"],["みんなが動けるか","T03","T10"]]},
 {scene:"急に注目されたとき",q:"あなたの商品がSNSで話題に。次にすることは？",a:[["もっと発信して広げる","T09","T04"],["注文をさばく仕組みを整える","T02","T03"],["品質を落とさないよう確認する","T07","T10"],["次の新商品を考える","T01","T05"]]},
 {scene:"お金に余裕ができたとき",q:"会社に使えるお金が増えた。何に使いたい？",a:[["新しい事業を始める","T01","T05"],["人を採って組織を強くする","T03","T09"],["設備や仕組みに使う","T02","T07"],["投資や買収も考える","T06","T10"]]},
 {scene:"お客様から苦情が来たとき",q:"最初に確かめたいことは？",a:[["何が一番つらかったか","T08","T04"],["商品に悪い所がなかったか","T07","T10"],["同じことが起きる仕組みになっていないか","T02","T03"],["自分の言葉で説明できるか","T09","T05"]]},
 {scene:"会社の未来を考えるとき",q:"5年後を想像して、いちばんワクワクするのは？",a:[["今はない仕事を生み出している","T01","T05"],["大勢の仲間と大きな仕事をしている","T03","T09"],["良い会社として長く続いている","T10","T07"],["お金と事業がうまく増えている","T06","T02"]]},
 {scene:"売上が止まったとき",q:"まず、どこから見直す？",a:[["お客様への伝え方","T04","T09"],["商品の中身","T07","T08"],["経費と仕事の流れ","T02","T06"],["新しい売り物や場所","T01","T05"]]},
 {scene:"仲間へお願いするとき",q:"仕事を任せるなら、何を一番伝える？",a:[["目指している未来","T05","T09"],["やり方と期限","T02","T10"],["任せたい役割","T03","T06"],["お客様に届けたい良さ","T07","T08"]]},
 {scene:"他社がまねしてきたとき",q:"あなたなら、どう動く？",a:[["さらに新しいことを始める","T01","T05"],["見せ方と売り方を変える","T04","T09"],["品質を上げて差をつける","T07","T10"],["規模や資金で先に進む","T06","T03"]]},
 {scene:"最後に、あなたの本音",q:"仕事を続ける一番の理由に近いのは？",a:[["面白い未来をつくりたい","T01","T05"],["誰かの役に立ちたい","T08","T07"],["強い会社を育てたい","T03","T06"],["大切な仕事を長く残したい","T10","T02"]]}
];

const ISSUES=["頭の中を整理したい","人にうまく伝えたい","もっと売りたい","人や組織を整えたい","お金の流れを良くしたい","商品を良くしたい","採用を進めたい","事業を長く続けたい"];
const ABILITIES={"開拓力":["T01","T05"],"組織力":["T03","T10"],"販売力":["T04","T09"],"資金力":["T02","T06"],"商品力":["T07","T04"],"継続力":["T08","T10"]};
let state={index:0,scores:{},answers:[],issues:[],tieDone:false};
Object.keys(TYPES).forEach(k=>state.scores[k]=0);
const $=s=>document.querySelector(s);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo({top:0,behavior:'smooth'});}
$('#startBtn').onclick=()=>show('profile');
$('#profileNext').onclick=()=>{state.name=$('#nameInput').value.trim()||'あなた';state.stage=$('#stageInput').value;show('quiz');renderQuestion();};
function renderQuestion(){const x=QUESTIONS[state.index];$('#progressText').textContent=`${state.index+1} / ${QUESTIONS.length}`;$('#progressBar').style.width=`${(state.index+1)/QUESTIONS.length*100}%`;$('#chapterText').textContent=state.index<4?'いつものあなた':state.index<8?'仕事が動いたとき':'これからのあなた';$('#questionScene').textContent=`場面：${x.scene}`;$('#questionText').textContent=x.q;$('#catTalk').textContent=['近い答えで大丈夫だよ。','正解はないから、いつもの自分でね。','考えすぎず、ぱっと選んでね。'][state.index%3];$('#answers').innerHTML='';x.a.forEach((a,i)=>{const b=document.createElement('button');b.className='answer-btn';b.innerHTML=`<b>${'ABCD'[i]}</b>${a[0]}`;b.onclick=()=>answer(x,a);$('#answers').appendChild(b);});}
function answer(q,a){state.scores[a[1]]+=3;state.scores[a[2]]+=1;state.answers.push({q:q.q,text:a[0],types:[a[1],a[2]]});state.index++;if(state.index<QUESTIONS.length)return renderQuestion();const rank=getRank();if(!state.tieDone&&rank[0][1]-rank[1][1]<=2)return renderTie(rank[0][0],rank[1][0]);renderIssues();}
function renderTie(a,b){state.tieDone=true;$('#progressText').textContent='最後の確認';$('#progressBar').style.width='100%';$('#questionScene').textContent='2つの型がとても近いです';$('#questionText').textContent='どちらの言葉が、より自分らしい？';$('#catTalk').textContent='迷ったときだけ聞く、おまけの一問だよ。';$('#answers').innerHTML='';[a,b].forEach((t,i)=>{const btn=document.createElement('button');btn.className='answer-btn';btn.innerHTML=`<b>${'AB'[i]}</b>${TYPES[t].tag}`;btn.onclick=()=>{state.scores[t]+=3;state.answers.push({q:'最後の確認',text:TYPES[t].tag,types:[t]});renderIssues();};$('#answers').appendChild(btn);});}
function renderIssues(){show('issues');$('#issueChoices').innerHTML='';ISSUES.forEach(x=>{const b=document.createElement('button');b.className='issue-choice';b.textContent=x;b.onclick=()=>{if(state.issues.includes(x)){state.issues=state.issues.filter(v=>v!==x);b.classList.remove('selected')}else if(state.issues.length<2){state.issues.push(x);b.classList.add('selected')}};$('#issueChoices').appendChild(b);});}
$('#showResult').onclick=renderResult;
function getRank(){return Object.entries(state.scores).sort((a,b)=>b[1]-a[1]);}
function getAbilities(){const max=Math.max(...Object.values(state.scores),1);const vals={};Object.entries(ABILITIES).forEach(([name,ids])=>{const raw=(state.scores[ids[0]]+state.scores[ids[1]])/2;vals[name]=Math.max(28,Math.min(96,Math.round(35+raw/max*61)));});return vals;}
function renderResult(){const rank=getRank(),main=rank[0][0],t=TYPES[main],abs=getAbilities();$('#resultName').textContent=state.name;$('#typeName').textContent=t.name;$('#typeTagline').textContent=t.tag;$('#typeRanking').innerHTML=rank.slice(0,3).map((x,i)=>`<span>${i+1}位 ${TYPES[x[0]].name}</span>`).join('');$('#strengthText').textContent=t.strength;$('#riskText').textContent=t.risk;$('#counterText').textContent=t.counter;$('#todayTitle').textContent=t.today;$('#todayText').textContent='10分だけ時間を取り、できたら誰か一人に見せてください。小さく動くほど、診断が実際の変化につながります。';const evidence=state.answers.filter(x=>x.types.includes(main)).slice(0,3);$('#evidenceIntro').textContent=`次の回答に「${t.name}」らしい考え方が強く表れていました。質問と、あなたが選んだ答えを並べて示します。`;$('#evidenceList').innerHTML=evidence.map(x=>`<div><p class="evidence-question">質問：${x.q}</p><b>あなたの回答：「${x.text}」</b><p>この選択が「${t.name}」の傾向として判定に反映されました。</p></div>`).join('')||'<p>全体の回答の組み合わせから判断しました。</p>';$('#abilityList').innerHTML=Object.entries(abs).map(x=>`<span>${x[0]}<b>${x[1]}点</b></span>`).join('');drawRadar(abs);$('#selectedIssues').innerHTML=(state.issues.length?state.issues:['今は特になし']).map(x=>`<span class="selected-issue-tag">${x}</span>`).join('');$('#issueAdvice').textContent=issueAdvice(state.issues);const needsStory=state.issues.some(x=>x.includes('整理')||x.includes('伝え'));$('#storyReason').textContent=needsStory?'今回の回答では「頭の中の整理」または「人に伝えること」が現在の課題として出ています。そのため、構想を物語に変えて共有する事業計画小説との相性が高いと考えられます。':'今すぐ必要とは限りません。ただ、事業の考えを社員や仲間へ共有する場面では、説明資料だけでなく「人が動く場面」を物語にする方法が使えます。';state.result={main,abs};show('result');}
function issueAdvice(xs){if(!xs.length)return'大きな困りごとがない時期こそ、得意な力を一つ伸ばすと次の準備になります。';if(xs.some(x=>x.includes('整理')||x.includes('伝え')))return'まず「誰に、何を分かってほしいか」を一人分だけ書きましょう。全部を説明しようとしないことがコツです。';if(xs.some(x=>x.includes('売り')))return'売り方を変える前に、最近のお客様一人へ「なぜ選んだか」を聞くと、使うべき言葉が見つかります。';if(xs.some(x=>x.includes('組織')||x.includes('採用')))return'仕事の説明より先に、何のための仕事かを一文にしてください。人は作業より目的で動きやすくなります。';return'一度に全部直さず、一番気になる数字か仕事を一つだけ選び、今週中に小さく試しましょう。';}
function drawRadar(vals){const c=$('#radar'),ctx=c.getContext('2d'),w=c.width,h=c.height,cx=w/2,cy=h/2+5,R=145,items=Object.entries(vals),n=items.length;ctx.clearRect(0,0,w,h);ctx.font='bold 16px Yu Gothic';ctx.textAlign='center';for(let ring=1;ring<=4;ring++){ctx.beginPath();items.forEach((_,i)=>{const a=-Math.PI/2+i*2*Math.PI/n,r=R*ring/4,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.strokeStyle='#ddd7ce';ctx.stroke()}items.forEach(([name],i)=>{const a=-Math.PI/2+i*2*Math.PI/n;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);ctx.strokeStyle='#e5dfd5';ctx.stroke();ctx.fillStyle='#333';ctx.fillText(name,cx+Math.cos(a)*(R+34),cy+Math.sin(a)*(R+25)+5)});ctx.beginPath();items.forEach(([,v],i)=>{const a=-Math.PI/2+i*2*Math.PI/n,r=R*v/100,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle='rgba(234,166,130,.45)';ctx.fill();ctx.lineWidth=4;ctx.strokeStyle='#d47d59';ctx.stroke();ctx.lineWidth=1;}
function shareData(){const d=state.result,u=new URL('share-result.html',location.href);u.searchParams.set('type',d.main);u.searchParams.set('name',state.name);u.searchParams.set('scores',Object.values(d.abs).join(','));return{url:u.href,text:`私は「${TYPES[d.main].name}」でした。${TYPES[d.main].tag}\nあなたはどんな社長？`};}
$('#nativeShare').onclick=async()=>{const d=shareData();if(navigator.share)await navigator.share({title:'ねこ社長の経営タイプ診断',text:d.text,url:d.url});else copyShare();};
$('#lineShare').onclick=()=>{const d=shareData();open(`https://line.me/R/msg/text/?${encodeURIComponent(d.text+'\n'+d.url)}`,'_blank')};
$('#xShare').onclick=()=>{const d=shareData();open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(d.text)}&url=${encodeURIComponent(d.url)}`,'_blank')};
async function copyShare(){const d=shareData();await navigator.clipboard.writeText(d.text+'\n'+d.url);$('#shareStatus').textContent='結果のリンクをコピーしました。';}
$('#copyShare').onclick=copyShare;$('#retryBtn').onclick=()=>location.reload();

